project:
  type: website

website:
  title: "William Becker"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: posts/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Publications
        href: publications/index.qmd
      - icon: github
        href: https://github.com/bluefoxr/
      - icon: linkedin
        href: https://www.linkedin.com/in/webecker/
  page-footer: "Copyright 2024, William Becker"
format:
  html:
    theme: yeti
    css: styles.css



